version: '2.1'
orbs:
  gh-pages: sugarshin/gh-pages@1.0.1
jobs:
  build_deploy:
    executor: gh-pages/default
    steps:
      - checkout
      - gh-pages/deploy:
          setup-git: true
          ssh-fingerprints: 5a:0a:a1:94:40:19:5c:21:94:07:ae:c7:8e:04:ba:96

workflows:
  Build and Deploy:
    jobs:
      - build_deploy
